# kubectl apply -f /usr/local/cbsd/modules/k8s.d/scripts/busybox.yaml
# kubectl exec -ti busybox -- nslookup kubernetes.default
# kubectl exec -ti busybox -- sh
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox:1.34
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always

