# persistentVolumeReclaimPolicy: 
#persistentVolumeReclaimPolicy - what will happen to pv after pvc is removed. There may be 3 options.
#
#    Retain - pv will not be deleted.
#    Recycle - pv will be cleaned.
#    Delete - pv will be deleted.
#
# to destroy
#   kubectl delete pv pvc-nfs
#
# Since we do not have a Provisioner for nfs, it will not work to delete pv automatically. So we only have 2 options - either retain the data (retain), or clean the volume (recycle).
# kubectl get pv
#kind: StorageClass
#apiVersion: storage.k8s.io/v1
#metadata:
#  name: %%PV_METADATA_NAME%%
#  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
#provisioner: %%PV_SPEC_SERVER%%%%PV_SPEC_NFS_PATH%%
#parameters:
#  archiveOnDelete: "false"
#mountOptions:
#  - vers=4.1

#--    - nfsvers=4.1
#++    - nfsvers=4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: %%PV_METADATA_NAME%%
spec:
  capacity:
    storage: %%PV_SPEC_CAPACITY_STORAGE%%Gi
  volumeMode: %%PV_SPEC_VOLUMEMODE%%
  accessModes:
    - %%PV_SPEC_ACCESSMODES%%
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    path: %%PV_SPEC_NFS_PATH%%
    server: %%PV_SPEC_SERVER%%
